import React from 'react'
import Head from 'next/head'

const Layout = ({title, children})=> {
    return (
      <>
          <Head>
            <title>Digimon Season 1 | {title}</title>
            <meta
              name="description"
              content="Generated by Digimon API and Next.js"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main>
              {children}
          </main>
      </>
    );
}

export default Layout