import Head from 'next/head'
import Card from '../components/Card';
import { getAllDigimon } from "../lib/digimon";
import Link from 'next/link'
import styled from 'styled-components';

const GridDiv = styled.div`
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
`

export default function Home({digimon}) {
  return (
    <div>
      <Head>
        <title>Digimon Season 1 List</title>
        <meta name="description" content="Generated by Digimon API and Next.js" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
       <h1>Welcome to Digimon API</h1>
       <GridDiv>
        {digimon.map(({name, level, img}) =>
          <Card 
            key={name}
            name={name}
            img={img}
            level={level}
          />
        )}
       </GridDiv>
      </main>

      <footer>
        <p>Viet Nguyen 2021</p>
      </footer>
    </div>
  )
}

export const getStaticProps = async () =>{
    try {
      const res = await fetch(`https://digimon-api.vercel.app/api/digimon/`);
      const digimon = await res.json();
      
      return {
        props: {
          digimon,
        },
      };
    } catch (err) {
      console.error(err, `error is happening`);
    }
}